# Generated by Django 3.2.6 on 2021-11-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0001_initial'),
        ('Vehicle', '0001_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('destination_1', models.CharField(max_length=15)),
                ('destination_2', models.CharField(max_length=15)),
                ('destination_3', models.CharField(max_length=15)),
                ('destination_4', models.CharField(max_length=15)),
                ('destination_5', models.CharField(max_length=15)),
                ('destination_6', models.CharField(max_length=15)),
                ('destination_7', models.CharField(max_length=15)),
                ('destination_8', models.CharField(max_length=15)),
                ('destination_9', models.CharField(max_length=15)),
                ('destination_10', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
                ('departure_time', models.CharField(max_length=15)),
                ('departure_loc', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
                ('estimated_time', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='Ready to deliver', max_length=30)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.driver')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.manifest')),
                ('routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travels.routes')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle')),
            ],
        ),
    ]
