# Generated by Django 3.2.6 on 2021-11-14 06:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDoc',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Driver.base')),
                ('license_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('license_no', models.CharField(max_length=15)),
                ('license_exp_date', models.DateField()),
                ('license_status', models.CharField(default='', max_length=15)),
                ('adharCard_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('adharCard_no', models.CharField(max_length=15)),
                ('panCard_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('panCard_no', models.CharField(max_length=15)),
                ('marritial_status', models.CharField(max_length=20)),
                ('driver_image', models.ImageField(default='', upload_to='drivers/images')),
            ],
            bases=('Driver.base',),
        ),
        migrations.CreateModel(
            name='DriverNote',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Driver.base')),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
            bases=('Driver.base',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Driver.base')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone1', models.IntegerField(default=0)),
                ('phone2', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=15)),
                ('branch', models.CharField(default='', max_length=15)),
                ('base_location', models.CharField(default='', max_length=15)),
                ('zip_code', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('driving_time', models.CharField(choices=[('Day', 'DAY'), ('Night', 'NIGHT'), ('Day + Night', 'DAY + Night')], default='day', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Engage', 'ENGAGE'), ('InActive', 'INACTIVE')], default='Active', max_length=10)),
                ('experience', models.CharField(choices=[('1', 'Less then 1 year'), ('2 - 4', 'Between 2 - 4 Years'), ('4 - 6', 'Between 4 - 6 Years'), ('6+', 'More than 6+ Years')], default='2 - 4', max_length=20)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('salary', models.IntegerField(default=0)),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.driverdoc')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.drivernote')),
            ],
            bases=('Driver.base',),
        ),
    ]
