# Generated by Django 3.2.6 on 2021-11-19 05:53

import Driver.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='base_location',
            field=models.CharField(default='', max_length=15, validators=[Driver.validations.name]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='branch',
            field=models.CharField(default='', max_length=15, validators=[Driver.validations.name]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=15, validators=[Driver.validations.name]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=15, validators=[Driver.validations.name]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone1',
            field=models.IntegerField(default=0, validators=[Driver.validations.phoneNumber]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone2',
            field=models.IntegerField(default=0, validators=[Driver.validations.phoneNumber]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='zip_code',
            field=models.IntegerField(default=0, validators=[Driver.validations.zipCode]),
        ),
        migrations.AlterField(
            model_name='driverdoc',
            name='adharCard_no',
            field=models.CharField(max_length=15, validators=[Driver.validations.adharCard]),
        ),
        migrations.AlterField(
            model_name='driverdoc',
            name='license_no',
            field=models.CharField(max_length=15, validators=[Driver.validations.license]),
        ),
        migrations.AlterField(
            model_name='driverdoc',
            name='panCard_no',
            field=models.CharField(max_length=15, validators=[Driver.validations.panCard]),
        ),
    ]
