# Generated by Django 3.2.6 on 2021-11-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_auto_20211119_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdoc',
            name='license_status',
        ),
    ]
