# Generated by Django 3.2.6 on 2021-11-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='', max_length=15)),
                ('owner_phone', models.IntegerField(default=0)),
                ('rc_book', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('papers_img', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('permit', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_service', models.DateField()),
                ('insurance_exp', models.DateField()),
                ('insurance_status', models.CharField(default='', max_length=15)),
                ('puc_exp', models.DateField()),
                ('puc_status', models.CharField(default='', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('ownerShip', models.CharField(choices=[('Company', 'COMPANY'), ('Joint Tenants', 'JOINT TENANTS'), ('Business Partners', 'BUISNESS PARTNERS')], default='Company', max_length=30)),
                ('vehicle_type', models.CharField(choices=[('Truck', 'TRUCK'), ('Mini Truck', 'MNI TRUCK'), ('Heavy Truck', 'HEAVY TRUCK'), ('Tempo', 'TEMPO'), ('Cargo', 'CARGO')], max_length=15)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'PETROL'), ('Diesel', 'DIESEL'), ('CNG', 'CNG'), ('Electric', 'ELECTRIC')], default='Diesel', max_length=15)),
                ('permit_type', models.CharField(choices=[('City', 'CITY'), ('State', 'STATE'), ('National', 'NATIONAL')], default='State', max_length=15)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Engage', 'ENGAGE'), ('InActive', 'INACTIVE')], default='Active', max_length=15)),
                ('capacity', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rc_number', models.CharField(default='', max_length=30)),
                ('vehicle_image', models.ImageField(default='', upload_to='vehicles/images')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicledoc')),
                ('maintainence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehiclemaintainance')),
            ],
        ),
    ]
