# Generated by Django 3.2.6 on 2021-11-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDoc',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Driver.base')),
                ('owner_name', models.CharField(default='', max_length=15)),
                ('owner_phone', models.IntegerField(default=0)),
                ('rc_book', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('papers_img', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('permit', models.ImageField(default='', upload_to='vehiclesDocs/images')),
            ],
            bases=('Driver.base',),
        ),
        migrations.CreateModel(
            name='VehicleMaintainance',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Driver.base')),
                ('last_service', models.DateField()),
                ('insurance_exp', models.DateField()),
                ('insurance_status', models.CharField(default='', max_length=15)),
                ('puc_exp', models.DateField()),
                ('puc_status', models.CharField(default='', max_length=15)),
            ],
            bases=('Driver.base',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Driver.base')),
                ('model', models.CharField(max_length=30)),
                ('ownerShip', models.CharField(choices=[('Company', 'COMPANY'), ('Joint Tenants', 'JOINT TENANTS'), ('Business Partners', 'BUISNESS PARTNERS')], default='Company', max_length=30)),
                ('vehicle_type', models.CharField(choices=[('Truck', 'TRUCK'), ('Mini Truck', 'MNI TRUCK'), ('Heavy Truck', 'HEAVY TRUCK'), ('Tempo', 'TEMPO'), ('Cargo', 'CARGO')], max_length=15)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'PETROL'), ('Diesel', 'DIESEL'), ('CNG', 'CNG'), ('Electric', 'ELECTRIC')], default='Diesel', max_length=15)),
                ('permit_type', models.CharField(choices=[('City', 'CITY'), ('State', 'STATE'), ('National', 'NATIONAL')], default='State', max_length=15)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Engage', 'ENGAGE'), ('InActive', 'INACTIVE')], default='Active', max_length=15)),
                ('carrying_capacity', models.CharField(default='', max_length=15)),
                ('carrying_space', models.CharField(default='', max_length=15)),
                ('length', models.FloatField(default=0)),
                ('breadth', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('rc_number', models.CharField(default='', max_length=30)),
                ('vehicle_image', models.ImageField(default='', upload_to='vehicles/images')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicledoc')),
                ('maintainence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehiclemaintainance')),
            ],
            bases=('Driver.base',),
        ),
    ]
