# Generated by Django 3.2.6 on 2021-11-19 05:53

import Vehicle.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_branch',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='vehiclemaintainance',
            name='insurance_policy_no',
            field=models.CharField(default='', max_length=12, validators=[Vehicle.validation.policyNumber]),
        ),
        migrations.AddField(
            model_name='vehiclemaintainance',
            name='puc_no',
            field=models.CharField(default='', max_length=12, validators=[Vehicle.validation.pucNumber]),
        ),
        migrations.AlterField(
            model_name='vehicledoc',
            name='owner_name',
            field=models.CharField(default='', max_length=15, validators=[Vehicle.validation.name]),
        ),
        migrations.AlterField(
            model_name='vehicledoc',
            name='owner_phone',
            field=models.IntegerField(default=0, validators=[Vehicle.validation.phoneNumber]),
        ),
    ]
