# Generated by Django 3.2.9 on 2021-11-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_auto_20211104_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='puc_exp',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_status',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_exp',
            field=models.CharField(max_length=15),
        ),
    ]
