# Generated by Django 3.2.6 on 2021-11-19 06:22

import Vehicle.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_auto_20211119_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='rc_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='no_plate',
            field=models.CharField(default='', max_length=30, validators=[Vehicle.validation.vehicleNumber]),
        ),
        migrations.AddField(
            model_name='vehicledoc',
            name='rc_number',
            field=models.CharField(default='', max_length=15, validators=[Vehicle.validation.rcNumber]),
        ),
    ]
