# Generated by Django 3.2.9 on 2021-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0003_auto_20211104_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
