# Generated by Django 3.2.6 on 2021-11-19 06:28

import Vehicle.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0003_auto_20211119_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledoc',
            name='owner_name',
            field=models.CharField(default='', max_length=15, validators=[Vehicle.validation.ownerName]),
        ),
    ]
