# Generated by Django 3.2.9 on 2021-11-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0004_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone1', models.IntegerField(default=0)),
                ('phone2', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('experience', models.CharField(max_length=20)),
                ('license_no', models.CharField(max_length=15)),
                ('license_exp_date', models.DateField()),
                ('license_status', models.CharField(default='', max_length=15)),
                ('marritial_status', models.CharField(max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('driver_image', models.ImageField(default='', upload_to='drivers/images')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.drivermsg')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle')),
            ],
        ),
    ]
