# Generated by Django 3.2.6 on 2021-11-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0004_alter_vehicledoc_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='no_plate',
            new_name='number_plate',
        ),
        migrations.RemoveField(
            model_name='vehiclemaintainance',
            name='insurance_status',
        ),
        migrations.RemoveField(
            model_name='vehiclemaintainance',
            name='puc_status',
        ),
    ]
