# Generated by Django 3.2.9 on 2021-11-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0005_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
