# Generated by Django 3.2.9 on 2021-11-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0006_auto_20211104_0905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverMsg',
        ),
    ]
