# Generated by Django 3.2.9 on 2021-11-04 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0008_courier_driver_drivermsg_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermsg',
            name='date',
        ),
        migrations.AlterField(
            model_name='drivermsg',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.time(9, 14, 50, 931341)),
        ),
    ]
