# Generated by Django 3.2.9 on 2021-11-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0009_auto_20211104_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='message',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='courier_name',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverMsg',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
