# Generated by Django 3.2.9 on 2021-11-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0011_courier_driver_drivermsg_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermsg',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
