# Generated by Django 3.2.9 on 2021-11-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0012_alter_drivermsg_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_fir_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_sec_name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
