# Generated by Django 3.2.9 on 2021-11-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0015_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='message',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='travels',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='travels',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='courier_name',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverMsg',
        ),
        migrations.DeleteModel(
            name='Travels',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
