# Generated by Django 3.2.9 on 2021-11-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehicle', '0016_auto_20211107_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sender_name', models.CharField(max_length=30)),
                ('reciver_name', models.CharField(max_length=30)),
                ('total_items', models.CharField(max_length=30)),
                ('total_ammount', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(max_length=10)),
                ('payment_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone1', models.IntegerField(default=0)),
                ('phone2', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('experience', models.CharField(max_length=20)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('license_no', models.CharField(max_length=15)),
                ('license_exp_date', models.DateField()),
                ('license_status', models.CharField(default='', max_length=15)),
                ('adharCard_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('adharCard_no', models.CharField(max_length=15)),
                ('panCard_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('panCard_no', models.CharField(max_length=15)),
                ('marritial_status', models.CharField(max_length=20)),
                ('driver_image', models.ImageField(default='', upload_to='drivers/images')),
            ],
        ),
        migrations.CreateModel(
            name='DriverMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='', max_length=15)),
                ('owner_phone', models.IntegerField(default=0)),
                ('rc_book', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('papers_book', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('permit', models.ImageField(default='', upload_to='vehiclesDocs/images')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_service', models.DateField()),
                ('insurance_exp', models.DateField()),
                ('insurance_status', models.CharField(default='', max_length=15)),
                ('puc_exp', models.DateField()),
                ('puc_status', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=30)),
                ('vehicle_status', models.CharField(max_length=15)),
                ('speed', models.CharField(max_length=15)),
                ('fuel_type', models.CharField(max_length=15)),
                ('mileage', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(max_length=15)),
                ('permit_type', models.CharField(max_length=15)),
                ('capacity', models.CharField(max_length=15)),
                ('rc_number', models.CharField(default='', max_length=30)),
                ('vehicle_image', models.ImageField(default='', upload_to='vehicles/images')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicledocs')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.driver')),
                ('maintainence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehiclemaintainance')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
                ('estimated_time', models.CharField(max_length=15)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.courier')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.driverdocs'),
        ),
        migrations.AddField(
            model_name='driver',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.drivermsg'),
        ),
    ]
