# Generated by Django 3.2.9 on 2021-11-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0017_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverDocs',
            new_name='DriverDoc',
        ),
        migrations.RenameModel(
            old_name='Travels',
            new_name='Travel',
        ),
        migrations.RenameModel(
            old_name='VehicleDocs',
            new_name='VehicleDoc',
        ),
    ]
