# Generated by Django 3.2.9 on 2021-11-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0020_manifest_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
