# Generated by Django 3.2.9 on 2021-11-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0021_drivermsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermsg',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
