# Generated by Django 3.2.9 on 2021-11-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0022_drivermsg_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone1', models.IntegerField(default=0)),
                ('phone2', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('experience', models.CharField(max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('license_no', models.CharField(max_length=15)),
                ('license_exp_date', models.DateField()),
                ('license_status', models.CharField(default='', max_length=15)),
                ('adharCard_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('adharCard_no', models.CharField(max_length=15)),
                ('panCard_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('panCard_no', models.CharField(max_length=15)),
                ('marritial_status', models.CharField(max_length=20)),
                ('driver_image', models.ImageField(default='', upload_to='drivers/images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='', max_length=15)),
                ('owner_phone', models.IntegerField(default=0)),
                ('rc_book', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('papers_book', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('permit', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_service', models.DateField()),
                ('insurance_exp', models.DateField()),
                ('insurance_status', models.CharField(default='', max_length=15)),
                ('puc_exp', models.DateField()),
                ('puc_status', models.CharField(default='', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Petrol', 'PETROL'), ('Diesel', 'DIESEL'), ('CNG', 'CNG'), ('Electric', 'ELECTRIC')], default='Diesel', max_length=15)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('vehicle_status', models.CharField(max_length=15)),
                ('fuel_type', models.CharField(max_length=15)),
                ('permit_type', models.CharField(max_length=15)),
                ('capacity', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rc_number', models.CharField(default='', max_length=30)),
                ('vehicle_image', models.ImageField(default='', upload_to='vehicles/images')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicledoc')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.driver')),
                ('maintainence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehiclemaintainance')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.manifest')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
                ('departure_time', models.CharField(max_length=15)),
                ('departure_loc', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
                ('estimated_time', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.driver')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.manifest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.driverdoc'),
        ),
        migrations.AddField(
            model_name='driver',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.drivermsg'),
        ),
    ]
