# Generated by Django 3.2.9 on 2021-11-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
        ('Vehicle', '0023_auto_20211108_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.driver'),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverDoc',
        ),
        migrations.DeleteModel(
            name='DriverMsg',
        ),
    ]
