# Generated by Django 3.2.9 on 2021-11-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
        ('Vehicle', '0024_auto_20211108_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='travel',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.manifest'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.manifest'),
        ),
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
