# Generated by Django 3.2.9 on 2021-11-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0025_auto_20211108_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
