# Generated by Django 3.2.9 on 2021-11-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0026_auto_20211108_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
