# Generated by Django 3.2.9 on 2021-11-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0028_travel_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_ownerShip',
            field=models.CharField(choices=[('Company', 'COMPANY'), ('Joint Tenants', 'JOINT TENANTS'), ('Business Partners', 'BUISNESS PARTNERS')], max_length=30),
        ),
    ]
