# Generated by Django 3.2.9 on 2021-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0029_alter_vehicle_vehicle_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='permit_type',
            field=models.CharField(choices=[('City', 'CITY'), ('State', 'STATE'), ('National', 'NATIONAL')], default='State', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_ownerShip',
            field=models.CharField(choices=[('Company', 'COMPANY'), ('Joint Tenants', 'JOINT TENANTS'), ('Business Partners', 'BUISNESS PARTNERS')], default='Company', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'TRUCK'), ('Mini Truck', 'MNI TRUCK'), ('Heavy Truck', 'HEAVY TRUCK'), ('Tempo', 'TEMPO'), ('Cargo', 'CARGO')], max_length=15),
        ),
    ]
