# Generated by Django 3.2.9 on 2021-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0030_auto_20211108_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Engage', 'ENGAGE'), ('InActive', 'INACTIVE')], default='Active', max_length=15),
        ),
    ]
