# Generated by Django 3.2.9 on 2021-11-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0032_auto_20211108_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='orders',
            new_name='manifest',
        ),
    ]
