# Generated by Django 3.2.9 on 2021-11-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0033_rename_orders_travel_manifest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledoc',
            old_name='papers_book',
            new_name='papers_img',
        ),
    ]
