# Generated by Django 3.2.9 on 2021-11-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0034_rename_papers_book_vehicledoc_papers_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
    ]
