# Generated by Django 3.2.9 on 2021-11-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0036_remove_vehicle_manifest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
